blockmod:
  active: true
  override_perm: "blockmod.over"
  raison: "Serveur non disponible, tenez vous au courant sur le forum/discord"
  
discord:
  token: ""

lobby:
   name: "lobby"
   message: "&6Teleportation au lobby..."

coins:
  url: "web.pumpmykins.eu"
  user: "pmk_coins"
  mdp: "mdp"
  database: "pmk_coins"