name: PMK-BungeeUtils
main: fr.pmk_bungeeutils.MainBungeeUtils
version: 1.0
author: Clem_Fern

commands:
  blockmod:
    description: Commande controlant le blockage
    usage: /blockmod
    
  support:
    description:  Commande de demande de support
  
  ensupport:  
    description:  Commande d activation de la visibilite ou non
  
  pmkbuyinfo:
    description: Commande d information d achat sur la boutique
    
  link:
    description: commande liaison discord
    
  lobby:
    description: commande de retour au lobby
    
  rules:
    description: commande d'affichage des règles
  
  aide:
    description: commande d'affichage des aides
  
  coins:
    description: Commande d'affichage du nombre de coins
    